spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:mariadb://localhost/locations
    username: locations
    password: locations

locations:
  name-auto-uppercase: true

logging:
  level:
    locations: debug

