spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:mariadb://localhost/locations
    username: locations
    password: locations

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  appname: Locations
  contact: info@example.com

locations:
  name-auto-uppercase: true
  event-store-url: http://localhost:8081/api/events

logging:
  level:
    locations: debug

