spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mariadb://localhost/locations
    username: locations
    password: locations

locations:
  name-auto-uppercase: true

logging:
  level:
    locations: debug

